feat: send btc
dwarvesf/icy-backend pull request #6
Opened 2024-11-08 11:42 UTC by anhnh12

#### What's this PR do?
- Implement func `btcrpc.Send`

2024-11-08 11:53 UTC, huynguyenh commented on internal/blockstream/blockstream.go
> +package blockstream
should we put it under 

internal/btcrpc/blockstream ?

2024-11-08 14:54 UTC, huynguyenh commented on internal/btcrpc/blockstream/blockstream.go
> +func (c *blockstream) GetFeeEstimates() (map[string]float64, error) {
```suggestion
func (c *blockstream) EstimateFee() (map[string]float64, error) {
```

2024-11-08 14:54 UTC, huynguyenh commented on internal/btcrpc/blockstream/blockstream.go
> +func (c *blockstream) GetFeeEstimates() (map[string]float64, error) {
what is the map[string]float64 stand for ?

2024-11-08 14:59 UTC, huynguyenh commented on internal/btcrpc/helper.go
> +	// Return minimum 1000 sats if calculated fee is too low
why we need to do this

2024-11-08 15:03 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	pubKeyHash := btcutil.Hash160(pubKey.SerializeCompressed())
move this to a helper function

```getPubKey```

```func getPubKeyHash(...) ... {
   pubKey := getPubKey()
   return pubKey.Hash160(...)
}```

2024-11-08 15:06 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	senderAddress, err := btcutil.NewAddressWitnessPubKeyHash(pubKeyHash, &chaincfg.TestNet3Params)
move this to a helper function too `getSelfAddress`

2024-11-08 15:06 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Fatal("failed to create sender address", map[string]string{
log Error only

2024-11-08 15:07 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Fatal("failed to get latest UTXO", map[string]string{
log error

2024-11-08 15:08 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	prevTxAmount := latestUTXO.Value
what's the purpose of getting this one ?

2024-11-08 15:08 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Fatal("failed to create recipient address", map[string]string{
log err then return

2024-11-08 15:09 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Fatal("failed to convert amount to big int", map[string]string{
log err then return

2024-11-08 15:09 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	txFee := int64(1000)
why hard code fee here ?

2024-11-08 15:09 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Fatal("insufficient funds in UTXO")
log err then return

2024-11-08 15:10 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	}
move from this line upto line 73 to another smaller function `VerifyBalanceBeforeSend`

2024-11-08 15:11 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	txIn := wire.NewTxIn(wire.NewOutPoint(hash, uint32(prevTxIndex)), nil, nil)
group this into 1 smaller function `CreateTx`

2024-11-08 15:12 UTC, huynguyenh requested changes

2024-11-08 15:12 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	txIn := wire.NewTxIn(wire.NewOutPoint(hash, uint32(prevTxIndex)), nil, nil)
why we create new tx with previous hash data ?

2024-11-10 17:57 UTC, anhnh12 commented on internal/btcrpc/blockstream/blockstream.go
> +func (c *blockstream) GetFeeEstimates() (map[string]float64, error) {
- key: number of target confirmation blocks
- value: fee rates (satoshis/vB)

a btc tx usually targets for 6 confirmation blocks

2024-11-10 18:08 UTC, anhnh12 commented on internal/btcrpc/btcrpc.go
> +	prevTxAmount := latestUTXO.Value
UTXO: Unspent tx output
A bitcoin transfer needs previous txs data as inputs. They can be used as proof to verify source of the btc amount you are trying to transfer.
e.g. transfer 1000 sats, need to refer to one or more previous txs where the sum of UTXOs amount >= 1000 sats

How it works
transfer amount = 1000 sats, use tx A as UTXO (1200 sats)
-> this UTXO is marked as spent, can no longer be used in other txs
-> 1200 spent -> changeAmount = 200 -> so we got a new UTXO as 200 sats

2024-11-12 02:37 UTC, merged