Feat/implement icy oracle
dwarvesf/icy-backend pull request #7
Opened 2024-11-10 14:54 UTC by nnhuyhoang

#### What's this PR do?

- [x]

2024-11-10 16:39 UTC, huynguyenh commented on migrations/schema/0001_add_locked_icy_treasury_table.up.sql
> +CREATE TABLE "icy_locked_treasuries" (
why we need this table ?

2024-11-10 17:20 UTC, baenv commented on devbox.json
> +        "echo 'Rolling back PostgreSQL migration...'",
Should we construct the URL using available Envs instead of adding another one? It lets the DB connection does not consistent.

2024-11-10 17:20 UTC, baenv commented on internal/store/icylockedtreasury/icy_locked_treasury.go
> +func (s *store) All(db *gorm.DB) ([]*model.IcyLockedTreasury, error) {
```go
return result,db.Find(&result).Error
```

2024-11-11 01:31 UTC, huynguyenh commented on contracts/icy/icy.abi
> +[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":true,"internalType
rename this file to erc20.abi

2024-11-11 01:33 UTC, huynguyenh commented on internal/model/web3_bigint.go
> +		Decimal: w.Decimal,
are we allowing 2 different BigInt with different Decimal ?

2024-11-11 01:33 UTC, huynguyenh commented on internal/model/web3_bigint.go
> +		Decimal: w.Decimal,
same comment as above

2024-11-11 01:34 UTC, huynguyenh commented on internal/model/web3_bigint.go
>  package model
add test file for this file

2024-11-11 01:35 UTC, huynguyenh commented on internal/oracle/oracle.go
> +		o.logger.Error("[IcyOracle][GetCirculatedICY]", map[string]string{
```suggestion
		o.logger.Error("[IcyOracle][ICYTotalSupply]", map[string]string{
```

2024-11-11 01:36 UTC, huynguyenh commented on internal/oracle/oracle.go
> +		o.logger.Error("[IcyOracle][GetCirculatedICY]", map[string]string{
```suggestion
		o.logger.Error("[GetCirculatedICY][ICyLockedTreasury]", map[string]string{
```

2024-11-11 01:39 UTC, huynguyenh commented on internal/oracle/oracle.go
> +	o.cachedICYBTC = &model.Web3BigInt{
create a internal function to handle this (this will require mutex lock to read/write

2024-11-11 01:40 UTC, huynguyenh commented on internal/oracle/oracle.go
> +	ratioFloat.Int(ratioInt)
create a new function `getConversionRatio(circulatedIcy, btcSupply)` and get it tested

2024-11-11 01:40 UTC, huynguyenh commented on internal/oracle/oracle.go
> +	if btcFloat == 0 {
why btc == 0 is considering error ?

2024-11-11 01:41 UTC, huynguyenh commented on internal/oracle/oracle.go
> +		Decimal: 18,
for the ratio, let's use decimal = 6 should be suffice

2024-11-11 01:42 UTC, huynguyenh commented on internal/store/icylockedtreasury/icy_locked_treasury.go
> +	return icyLockedTreasuries, nil
```suggestion
 	return icyLockedTreasuries, db.Find(&icyLockedTreasuries).Error
```

2024-11-11 01:43 UTC, huynguyenh commented on internal/store/icylockedtreasury/interface.go
> +	"gorm.io/gorm"
order import as 

import (
     <native>

      <external package>


      <internal package>
)

2024-11-11 01:43 UTC, huynguyenh commented on internal/store/postgres/postgres.go
> +	DB *gorm.DB
why we need this to public ?

2024-11-11 01:44 UTC, huynguyenh commented on Makefile
> +migrate:
migrate-up

2024-11-11 01:44 UTC, huynguyenh commented on devbox.json
> +    "DB_URL": "postgresql://postgres:postgres@localhost:25432/icy_backend_local?sslmode=disable"
this one is no needed

2024-11-11 01:45 UTC, huynguyenh commented on internal/baserpc/baserpc.go
> +	"github.com/ethereum/go-ethereum/ethclient"
order import (see other comment)

2024-11-11 01:46 UTC, huynguyenh commented on internal/baserpc/interface.go
> +type IBaseRpc interface {
```suggestion
type IBaseRPC interface {
```

either using this or change other variables (see you use ICY, BTC, ...) to this convention

2024-11-11 01:46 UTC, huynguyenh commented on internal/baserpc/interface.go
> +	ICYBalanceOf(address string) (*model.Web3BigInt, error)
do we need to public IcyBalanceOf function ? seems like we only need TotalSupply, this BalaceOf will be internal ?

2024-11-11 01:48 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
>  func (b *BtcRpc) BalanceOf(address string) (*model.Web3BigInt, error) {
don't support this call, this will complex the caller (caller need to understand to call a right address to know BTC balance 

for this case, we just need something like `CurrentBalance()` ? (caller only need to know the current balance of btc treasury)

2024-11-11 01:49 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		Decimal: 10,
check if btc is indeed decimal 10

2024-11-11 01:50 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		Value:   strconv.Itoa(response.ChainStats.FundedTxoSum),
do we need to check UTXO too, cc @anhnh12

2024-11-11 01:50 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	resp, err := b.client.Get(url)
move from this line to different internal function

2024-11-11 01:50 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Error("[BtcRpc][BalanceOf]", map[string]string{
change log convention (see other comment)

2024-11-11 01:51 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +		b.logger.Error("[BtcRpc][BalanceOf]", map[string]string{
same as above

2024-11-11 01:52 UTC, huynguyenh commented on internal/btcrpc/btcrpc.go
> +	}
this function should handle retry for few times (let's try with 3), reason is rpc is not stable so we might need to retry for some use cases

2024-11-11 01:52 UTC, huynguyenh commented on internal/btcrpc/type.go
> +type MempoolStats struct {
can you add a comment show what is a different between MempoolStats and ChainStats

2024-11-11 01:52 UTC, huynguyenh commented on internal/model/web3_bigint.go
>  // TODO: add other utility functions for Web3BigInt
help to remove this comment

2024-11-11 01:53 UTC, huynguyenh commented on internal/store/icylockedtreasury/icy_locked_treasury.go
> +	"gorm.io/gorm"
order import

2024-11-11 01:53 UTC, huynguyenh commented on internal/server/server.go
> +	oracle := oracle.New(db.DB, s, appConfig, logger, btcRpc, baseRpc)
we we need to pass db.DB here ?

2024-11-11 01:55 UTC, huynguyenh commented on internal/oracle/oracle.go
> +	database     *gorm.DB
```suggestion
	db     *gorm.DB
```

2024-11-11 01:56 UTC, huynguyenh commented on internal/store/postgres/postgres.go
>  	return &PostgresStore{
can we just return `conn` here

2024-11-11 01:57 UTC, huynguyenh requested changes
please check comments

2024-11-11 02:44 UTC, nnhuyhoang commented on migrations/schema/0001_add_locked_icy_treasury_table.up.sql
> +CREATE TABLE "icy_locked_treasuries" (
it store the list of address which keep locked icy. So `circulated_icy = total_supply - sum(locked_icy)`

2024-11-11 03:17 UTC, huynguyenh commented on internal/oracle/oracle.go
> +	if btcFloat == 0 {
it should be ratio = 0 instead of return error

2024-11-11 03:30 UTC, nnhuyhoang commented on internal/baserpc/interface.go
> +	ICYBalanceOf(address string) (*model.Web3BigInt, error)
Don't we need it for Oracle can call to get ICY balance of locked addresses ?

2024-11-11 03:41 UTC, nnhuyhoang commented on internal/btcrpc/btcrpc.go
> +		Decimal: 10,
not understand, even len(value) < 10, it is still valid right ? 100000 =  0.00001

2024-11-11 04:04 UTC, nnhuyhoang commented on internal/server/server.go
> +	oracle := oracle.New(db.DB, s, appConfig, logger, btcRpc, baseRpc)
don't we need it to call to db layer in oracle ?

2024-11-19 03:28 UTC, merged